server:
  port: 8000


spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: api-member
          uri: http://localhost:9090
          predicates:
            - Path=/member/**
        - id: api-order
          uri: http://localhost:9091
          predicates:
            - Path=/order/**
        - id: api-product
          uri: http://localhost:9092
          predicates:
            - Path=/product/**




eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true